# Generated by Django 4.2.13 on 2024-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='explorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.IntegerField()),
                ('mapping_desc', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=20)),
                ('date_id', models.DateField()),
            ],
        ),
    ]
